### ISSUE TITLE
https私有仓库不可用

### ISSUE THREAD

**Issue by 4781121** [humpback/humpback-web#1]
我的https私有仓库pull push都是可以的, 但是humpback hub显示没内容.

**Comment by lon-yang** [comment]
在hub页面应该有一个 https://{PrivateRegistryAddress}/v2/_catalog 的请求出去，你在控制台看一下这个请求正常不？

**Comment by 4781121** [comment]
1. https://{PrivateRegistryAddress}/v2/_catalog 在控制台现实是正常的, 仓库是有image的, 内容是{"repositories":["base"]}, 没有错误
2. hub页面右上角显示个alert, 内容是Get images failed.

**Comment by lon-yang** [comment]
那控制台应该有类似于 [Thu Jun 22 2017 20:57:59 GMT+0800 (中国标准时间)] Get images from hub(gdev) failed. Err: TestError 这样的输出吧

**Comment by 4781121** [comment]
没有

**Comment by 4781121** [comment]
基本情况是, humpback和private registry使用的是同一服务商同一位置的2台虚拟主机, 都绑定了域名, private registry是https的, 大概就是这样的情况. 服务商是vultr

**Comment by lon-yang** [comment]
这个现象有点奇怪，因为这里如果出错的话，控制台会打印一条log出来
https://github.com/humpback/humpback-web/blob/master/src/client/app/pages/hub/hub-home/hub-home.page.ts#L63-L64
我再查一下

**Comment by 4781121** [comment]
哦太抱歉了, 我理解错误, 我是自己去控制台curl https://{PrivateRegistryAddress}/v2/_catalog这个地址的, 不是看的humpback的控制台, 我现在再去试下

**Comment by 4781121** [comment]
你说的Log是在Humpback -> Group -> Server - > Container Logs这个吗?
内容是:
/22 13:39:46.229] [LOG] Init system...
/22 13:39:46.300] [LOG] Init system succeed
/22 13:39:46.303] [LOG] Humpback Website is started on port 50000
我点hub没什么log更新

**Comment by lon-yang** [comment]
不是，是浏览器的控制台

**Comment by 4781121** [comment]
怎么看?

**Comment by lon-yang** [comment]
按F12打开控制台，然后点击进入hub页面，应该就会出现下面这样的输出
![image](https://user-images.githubusercontent.com/9428909/27437866-28357e8e-5796-11e7-8757-feca988d0d6f.png)

**Comment by 4781121** [comment]
XMLHttpRequest cannot load https://__PRIVATE_REGISTRY_URL__/v2/_catalog?n=1000. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://__HUMPBACK_WEB_RUL__' is therefore not allowed access.
app.011c80d11f5673fa6710.js:155 [Thu Jun 22 2017 22:06:22 GMT+0800 (中国标准时间)] Get images from hub(gdev) failed. Err: {"message":"Server is no response"}

**Comment by lon-yang** [comment]
这个是由于私有仓库的API没有配置允许跨域访问的原因
具体可以参考这篇文章进行设置 http://www.cnblogs.com/humin/p/6970212.html，设置好了应该就没问题了
![image](https://user-images.githubusercontent.com/9428909/27438416-c17b35ba-5797-11e7-9308-e2f449c87bcd.png)

**Comment by 4781121** [comment]
明白原因了, 非常感谢!
