### ISSUE TITLE
我想问下这个日志是存放在哪？

### ISSUE THREAD

**Issue by station19** [humpback/humpback-web#4]
![333](https://user-images.githubusercontent.com/4527618/32314663-f1b3a6e0-bfe3-11e7-9502-1ba404084033.png)

怎么会有这么多 连接 timeout，我没开集群... #

**Comment by lon-yang** [comment]
日志是docker自己管理的，这里是直接使用的docker的接口获取，和在shell里面调用的 docker logs <container> 看到的logs是一样的

**Comment by station19** [comment]
我是按照 http://www.cnblogs.com/humin/p/6859690.html 这个教程，应该是你们自己写的

是按照如下这样写吗？ 有没有详细的操作文档 ？
docker run -d -ti --net=host --restart=always \
-e DOCKER_API_VERSION=v1.19 \
-e DOCKER_CLUSTER_ENABLED=false \
-v /var/run/:/var/run/:rw \
--name=humpback-agent \
humpbacks/humpback-agent:1.2.4

**Comment by lon-yang** [comment]
可以参考这里的文档 https://humpback.github.io/humpback/#/zh-cn/run-humpback-agent

**Comment by station19** [comment]
6666   3Q
