### ISSUE TITLE
用humpback-web新建容器时总是无法启动

### ISSUE THREAD

**Issue by station19** [humpback/humpback-web#5]
必须先 在 服务器里 启动容器后，然后再到 humpback-web 管理 重启，停止等，

如果直接用 humpback-web 添加新容器，无法启动

刚开始以为是 容器镜像问题，然后从国内加速器 新下载 docker pull daocloud.io/library/centos:6.9

也是这样，请问有什么解决方法嘛？
![333](https://user-images.githubusercontent.com/4527618/32320303-3cc2bf4a-bff8-11e7-9086-be05d4f08f17.png)

手动启动 命令 ： docker run -td centos69 /bin/bash
![image](https://user-images.githubusercontent.com/4527618/32320432-ba9c18a8-bff8-11e7-8725-09812185a014.png)

**Comment by lon-yang** [comment]
这个应该是由于通过humpback创建的容器不会指定`OpenStdIn`参数导致docker没有虚拟化一个`tty`窗口出来，所以容器一运行就退出了。对于一般的应用程序是不会有影响的

**Comment by station19** [comment]
那有没有什么办法解决？ 我试了好几个docker上的镜像 都是这样

**Comment by lon-yang** [comment]
都是执行/bin/bash程序吗？这个需要修改humpback-agent的代码

**Comment by station19** [comment]
也不一定， 要是能自己指定参数启动就好了

**Comment by lon-yang** [comment]
可能是我们在使用的时候没有遇到过这种需求，然后docker参数又比较多就忽略了一部分，如果确实需要的话，我们可以后面处理一下

**Comment by station19** [comment]
好的，多谢了，那麻烦记录后续处理下。。。

**Comment by lon-yang** [comment]
好的

**Comment by station19** [comment]
nice

**Comment by lon-yang** [comment]
https://github.com/humpback/humpback-agent/issues/1

**Comment by station19** [comment]
启动agent的shih指定 -it ?

**Comment by station19** [comment]
在服务器手动启动的时候 是可以这样。。。没有问题，只是用 humpback-web 新建启动的时候 不好办

**Comment by lon-yang** [comment]
恩，所以需要humpback-agent在创建容器的时候指定这两个参数，要修改代码

**Comment by station19** [comment]
嗯好的。那就麻烦后续修改下了

**Comment by station19** [comment]
记得通知我啊 ^_^

**Comment by lon-yang** [comment]
:heavy_check_mark:
